"""
YOLO fine-tuning logic for the active learning pipeline.

Wraps the ultralytics training API and manages per-round model checkpoints.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class Trainer:
    """Fine-tune a YOLO model on user-corrected annotations.

    Parameters
    ----------
    project_dir:
        Root directory where training runs are saved (e.g. ``"runs"``).
    """

    #: Default epochs for the first (round 0) training run.
    DEFAULT_EPOCHS_FIRST: int = 50
    #: Default epochs for subsequent fine-tuning rounds.
    DEFAULT_EPOCHS_SUBSEQUENT: int = 30

    def __init__(self, project_dir: str = "runs") -> None:
        self.project_dir = Path(project_dir)
        self.project_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def train(
        self,
        data_yaml: str,
        base_model: str = "yolov8n.pt",
        round_number: int = 0,
        epochs: Optional[int] = None,
        imgsz: int = 640,
        batch: int = 16,
        device: str = "",
    ) -> str:
        """Fine-tune a YOLO model and return the path to the best checkpoint.

        Parameters
        ----------
        data_yaml:
            Path to the ``dataset.yaml`` file generated by
            :class:`~annotator.AnnotationManager`.
        base_model:
            Path to the starting weights (pretrained or previous round's
            best checkpoint).
        round_number:
            Current active learning round.  Used to name the output
            directory (e.g. ``runs/round_0``).
        epochs:
            Number of training epochs.  Defaults to 50 for round 0 and 30
            for subsequent rounds.  Aggressive augmentation is applied
            automatically when the training set is small.
        imgsz:
            Training image size.
        batch:
            Training batch size.
        device:
            Device string (e.g. ``"0"``, ``"cpu"``).  Empty string lets
            ultralytics auto-select.

        Returns
        -------
        str
            Path to the ``best.pt`` weights file produced by this run.

        Raises
        ------
        RuntimeError
            If training fails or no ``best.pt`` is produced.
        """
        try:
            from ultralytics import YOLO  # type: ignore
        except ImportError as exc:  # pragma: no cover
            raise ImportError(
                "ultralytics is required. Install it with: pip install ultralytics"
            ) from exc

        # Determine epoch count
        if epochs is None:
            epochs = self.DEFAULT_EPOCHS_FIRST if round_number == 0 else self.DEFAULT_EPOCHS_SUBSEQUENT

        run_name = f"round_{round_number}"
        run_dir = self.project_dir / run_name

        logger.info(
            "Starting training: round=%d, base=%s, epochs=%d, data=%s",
            round_number,
            base_model,
            epochs,
            data_yaml,
        )

        model = YOLO(base_model)

        # Build kwargs dynamically so we can handle device="" cleanly
        train_kwargs = dict(
            data=str(data_yaml),
            epochs=epochs,
            imgsz=imgsz,
            batch=batch,
            project=str(self.project_dir),
            name=run_name,
            exist_ok=True,
            verbose=True,
        )
        if device:
            train_kwargs["device"] = device

        model.train(**train_kwargs)

        best_pt = run_dir / "weights" / "best.pt"
        if not best_pt.exists():
            # ultralytics sometimes appends a suffix when exist_ok=True
            candidates = list(self.project_dir.glob(f"{run_name}*/weights/best.pt"))
            if candidates:
                best_pt = sorted(candidates)[-1]
            else:
                raise RuntimeError(
                    f"Training finished but best.pt not found under {run_dir}"
                )

        logger.info("Training complete. Best model: %s", best_pt)
        return str(best_pt)

    def copy_best_model(self, best_pt: str, dest_name: str) -> str:
        """Copy a ``best.pt`` to a stable named path.

        Parameters
        ----------
        best_pt:
            Source checkpoint path.
        dest_name:
            Destination filename (placed in ``self.project_dir``).

        Returns
        -------
        str
            Path to the copied file.
        """
        dest = self.project_dir / dest_name
        shutil.copy2(best_pt, dest)
        logger.info("Copied %s → %s", best_pt, dest)
        return str(dest)
